name: user_repo
description: A Repo handling users
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  firebase_auth: ^4.16.0
  cloud_firestore: ^4.9.2
  rxdart: ^0.27.7

flutter:
  uses-material-design: true
